#!/usr/bin/env python3
"""Stage 5: Validate experiment records and generate summary reports."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src import helpers

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--records", default=str(helpers.EXPERIMENT_RECORDS_CSV))
    parser.add_argument("--verbose", action="store_true")
    return parser.parse_args()

def count_candidate_json() -> int:
    total = 0
    for path in helpers.INTERMEDIATE_JSON_DIR.glob("*_candidate_snippets.json"):
        import json
        try:
            total += len(json.loads(path.read_text(encoding="utf-8")))
        except Exception:
            continue
    return total

def main() -> int:
    args = parse_args()
    helpers.setup_logging(args.verbose)
    
    records_path = Path(args.records)
    if not records_path.is_absolute():
        records_path = helpers.PROJECT_ROOT / records_path

    records = helpers.read_csv_or_empty(records_path, helpers.EXPERIMENT_COLUMNS)
    errors, warnings = helpers.validate_records(records)
    
    if errors.empty:
        errors = pd.DataFrame(columns=helpers.VALIDATION_COLUMNS)
    if warnings.empty:
        warnings = pd.DataFrame(columns=helpers.VALIDATION_COLUMNS)
        
    helpers.write_csv(errors, helpers.PROJECT_ROOT / "validation_errors.csv")
    helpers.write_csv(warnings, helpers.PROJECT_ROOT / "validation_warnings.csv")
    
    validation_report_content = f"""# Validation Report

## Input
- records: {records_path}
- record_count: {len(records)}

## Summary
- errors: {len(errors)}
- warnings: {len(warnings)}

## Notes
Required fields, numeric ranges, controlled vocabularies, granularity indicators, and provenance fields were checked. Candidate rows generated by automated mining are expected to require manual correction before becoming final records.
"""
    helpers.write_text(validation_report_content, helpers.PROJECT_ROOT / "validation_report.md")
    
    # Report compilation logic
    sources = helpers.read_csv_or_empty(helpers.DEFAULT_SOURCES_CSV, helpers.SOURCE_COLUMNS)
    time_series = helpers.read_csv_or_empty(helpers.TIME_SERIES_CSV, helpers.TIME_SERIES_COLUMNS)
    tables = helpers.read_csv_or_empty(helpers.TABLES_INDEX_CSV, helpers.TABLE_INDEX_COLUMNS)
    figures = helpers.read_csv_or_empty(helpers.FIGURES_INDEX_CSV, helpers.FIGURE_INDEX_COLUMNS)
    ambiguous = helpers.read_csv_or_empty(helpers.AMBIGUOUS_CASES_CSV, helpers.AMBIGUOUS_COLUMNS)
    excluded = helpers.read_csv_or_empty(helpers.EXCLUDED_RECORDS_CSV, helpers.EXCLUDED_COLUMNS)
    download_log = helpers.read_csv_or_empty(helpers.DOWNLOAD_LOG_CSV, helpers.DOWNLOAD_LOG_COLUMNS)
    manual_queue = helpers.read_csv_or_empty(helpers.MANUAL_DOWNLOAD_QUEUE_CSV, helpers.MANUAL_QUEUE_COLUMNS)
    
    processed_text = len(list(helpers.EXTRACTED_TEXT_DIR.glob("*.md")))
    downloaded = len(download_log[download_log["status"] == "success"]) if len(download_log) else 0
    manual_required = len(manual_queue)
    
    missing_stats = []
    for column in helpers.EXPERIMENT_COLUMNS:
        if len(records) == 0:
            missing = 0
        else:
            missing = int((records[column].fillna("").astype(str).str.strip() == "").sum())
        missing_stats.append(f"- {column}: {missing}")

    summary_content = f"""# Extraction Summary

## Goal
Practice 3 extracts experiment-level evidence for photocatalytic degradation of organic dyes from local scientific PDFs and supplementary files while preserving provenance, uncertainty, and excluded cases.

## Selected Sources
- total_sources: {len(sources)}
- primary_sources: {len(sources[sources['extraction_role'] == 'primary']) if len(sources) else 0}
- optional_sources: {len(sources[sources['extraction_role'] == 'optional']) if len(sources) else 0}

## Processed Files
- successful_downloads_or_html_saves: {downloaded}
- manual_download_queue_rows: {manual_required}
- extracted_text_files: {processed_text}
- extracted_tables: {len(tables)}
- figure_inventory_rows: {len(figures)}

## Candidate And Final Records
- candidate_snippets: {count_candidate_json()}
- experiment_record_rows: {len(records)}
- time_series_rows: {len(time_series)}

## Ambiguity And Exclusions
- ambiguous_cases: {len(ambiguous)}
- excluded_records: {len(excluded)}

## Validation
- validation_errors: {len(errors)}
- validation_warnings: {len(warnings)}

## Missing Field Statistics
{chr(10).join(missing_stats)}

## Limitations
This pipeline is intentionally semi-automatic. It inventories text, tables and figures, mines candidate snippets, and prepares a manual review workbook. It does not create high-confidence final records from weak snippets, and it does not automatically digitize plots.

## Input Preparation
See `inputs/download_log.csv`, `inputs/manual_download_queue.csv`, and `reports/input_inventory_report.md` for automatic acquisition status and manual fallback instructions.

## Next Steps
- Practice 4: use repository/web sources only as separate metadata/background evidence.
- Practice 5: clean, normalize, document license constraints, and prepare publication-ready dataset artifacts.
"""
    helpers.write_text(summary_content, helpers.PROJECT_ROOT / "extraction_summary.md")

    readme_content = f"""# Practice 3 PDF Extraction

Runnable Python pipeline for Practice 3 of the Extraction and preparation of chemical information course.

## Scope
One record is one independent photocatalytic degradation experiment for one organic dye under one fixed set of conditions. PDF/article/supplement extraction is the primary evidence source.

## Current Status
- selected_sources: {len(sources)}
- successful_downloads_or_html_saves: {downloaded}
- manual_download_queue_rows: {manual_required}
- extracted_text_files: {processed_text}
- extracted_tables: {len(tables)}
- figure_inventory_rows: {len(figures)}
- candidate_snippets: {count_candidate_json()}
- experiment_record_rows: {len(records)}
- ambiguous_cases: {len(ambiguous)}
- excluded_records: {len(excluded)}

## Run

```bash
pip install -r requirements.txt
python scripts/01_acquire_and_validate.py
python scripts/02_extract_content.py
python scripts/03_mine_candidates.py
python scripts/04_build_workbook.py
# Use practice3_manual_review.xlsx to manually review, edit, and save
python scripts/05_validate_and_report.py
```

## Manual Review
Use `practice3_manual_review.xlsx` to convert candidate snippets into final experiment-level records. Keep time-series points in `extracted_time_series_optional.csv`, not as separate main records.
"""
    helpers.write_text(readme_content, helpers.PROJECT_ROOT / "README_Practice3.md")
    
    print("Validation reports and metrics summary generated successfully.")
    print(f"Validation errors: {len(errors)}, Warnings: {len(warnings)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
